// <auto-generated />
using System;
using BonusPointManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BonusPointManager.Migrations
{
    [DbContext(typeof(BonusPointManagerContext))]
    [Migration("20220521191407_AddPointTypeTable")]
    partial class AddPointTypeTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BonusPointManager.Models.Eurobonus.EurobonusPointType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("PointType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EurobonusPointType");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            PointType = "Extra"
                        },
                        new
                        {
                            Id = 1,
                            PointType = "Basic"
                        },
                        new
                        {
                            Id = 2,
                            PointType = "Status"
                        });
                });

            modelBuilder.Entity("BonusPointManager.Models.Eurobonus.EurobonusTransaction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("AcquiredDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PointType")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("EurobonusTransaction");
                });
#pragma warning restore 612, 618
        }
    }
}
