// <auto-generated />
using System;
using BonusPointManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BonusPointManager.Migrations
{
    [DbContext(typeof(BonusPointManagerContext))]
    [Migration("20220522190246_LinkTransactionsAndEurobonusAccount")]
    partial class LinkTransactionsAndEurobonusAccount
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BonusPointManager.Models.Eurobonus.EurobonusAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccountNumber")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SignupDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EurobonusAccounts");
                });

            modelBuilder.Entity("BonusPointManager.Models.Eurobonus.EurobonusPointType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("PointType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EurobonusPointTypes");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            PointType = "Extra"
                        },
                        new
                        {
                            Id = 1,
                            PointType = "Basic"
                        },
                        new
                        {
                            Id = 2,
                            PointType = "Status"
                        });
                });

            modelBuilder.Entity("BonusPointManager.Models.Eurobonus.EurobonusStatusLevel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("StatusLevel")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EurobonusStatusLevels");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            StatusLevel = "Basic"
                        },
                        new
                        {
                            Id = 1,
                            StatusLevel = "Silver"
                        },
                        new
                        {
                            Id = 2,
                            StatusLevel = "Gold"
                        },
                        new
                        {
                            Id = 3,
                            StatusLevel = "Diamond"
                        },
                        new
                        {
                            Id = 4,
                            StatusLevel = "Pandion"
                        });
                });

            modelBuilder.Entity("BonusPointManager.Models.Eurobonus.EurobonusTransaction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AcquiredDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PointType")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AccountId");

                    b.ToTable("EurobonusTransactions");
                });

            modelBuilder.Entity("BonusPointManager.Models.Eurobonus.EurobonusTransaction", b =>
                {
                    b.HasOne("BonusPointManager.Models.Eurobonus.EurobonusAccount", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");

                    b.Navigation("Account");
                });
#pragma warning restore 612, 618
        }
    }
}
